[theme]
primaryColor = "#33cc33"  # A vibrant green for interactive elements
backgroundColor = "#1a1a1a"  # A dark background for modern contrast
secondaryBackgroundColor = "#262626"  # A slightly lighter shade for the sidebar and widgets
textColor = "#FFFFFF"  # White text for readability against the dark background
font = "sans serif"  # A clean, modern font choice


# Font style and size
base = "light"
